# Generated by Django 2.2.1 on 2019-05-26 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 13, 55, 49, 406537))),
                ('edit_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 13, 55, 49, 406553))),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(default=datetime.datetime(2019, 5, 26, 13, 55, 49, 405981))),
                ('rating', models.IntegerField(default=0)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ask.User'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('creation_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 13, 55, 49, 408063))),
                ('edit_date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 26, 13, 55, 49, 408080))),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.User')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='AnswerLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ask.User')),
            ],
            options={
                'unique_together': {('user', 'answer')},
            },
        ),
    ]
